### ISSUE TITLE
 Encounter InvalidURL Exception When Running WavCraft with Specific Input

### ISSUE THREAD

**Issue by arwooy** [JinhuaLiang/WavCraft#1]
run the following command:
python3 WavCraft.py basic -f --input-wav assets/duck_quacking_in_water.wav --input-text "Add dog barking."
Observe the InvalidURL exception in the output.

(WavCraft) ubuntu@ip-172-31-75-144:~/github/WavCraft$ python3 WavCraft.py basic -f --input-wav assets/duck_quacking_in_water.wav --input-text "Add dog barking."
New session created, session_id=20240329170307_i8mwewiu
Session 20240329170307_i8mwewiu is created.
session_id=20240329170307_i8mwewiu, Step 1: Writing executable code with LLM ...
    trying ...
session_id=20240329170307_i8mwewiu, Step 2: Start running Python program...
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/util/url.py", line 425, in parse_url
    host, port = _HOST_PORT_RE.match(host_port).groups()  # type: ignore[union-attr]
AttributeError: 'NoneType' object has no attribute 'groups'

The above exception was the direct cause of the following exception:

**Comment by JinhuaLiang** [comment]
Hi, thanks for your interests in our work. Please could you double check if you hosting the generative models on the local correctly?
